name: Patrick Meisch
favicon: null
layout_spectrum: 0.75827
typography_spectrum: 0.7454
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2e58c2'
    - '#050815'
    - '#fefeff'
    - '#937b7d'
    - '#d49b00'
  brandStrength: 0.4157706
  lightness: 0.530466
  saturation: 0.5035842
  rhythmicContrast: 0.2240143
purpose: []
